### ISSUE TITLE
New Metadata

### ISSUE THREAD

**Issue by KGB-USSR** [MrBukLau/mp3tag-web-sources-scripts#1]
Please add the following tags: LABEL (recordLabel), TRACKTOTAL (trackCount), UPC (upc). Thank you in advance.

**Comment by MrBukLau** [comment]
For the TRACKTOTAL (trackCount) tag, you can add this piece of code under the attributes object:
```
json_select "trackCount"
OutputTo "TOTALTRACKS"
SayNextNumber
Say "|"
```
You can place this code after the copyright code or anywhere in this area. I chose not to put this code in the Apple Music script because the number that it gets doesn't account for when an album has multiple discs, unlike the iTunes Store script.

For the LABEL (recordLabel) and UPC (upc) tags, I don't think it's possible to get the metadata for them. You could go to the forum page on Mp3tag Community and ask people there if it's possible to get these tags using the Apple Music API.

**Comment by MrBukLau** [comment]
Oops, I take that back.

Record Label Code:
```
json_select "recordLabel"
OutputTo "LABEL"
SayRest
Say "|"
```

UPC Code:
```
json_select "upc"
OutputTo "UPC"
SayRest
Say "|"
```

I'll add all three of these codes in the Apple Music script, but I'll comment them out. You'll have to remove the # symbols if you want to use these codes.
