### ISSUE TITLE
Copyright Field

### ISSUE THREAD

**Issue by egxl** [MrBukLau/mp3tag-web-sources-scripts#5]
The copyright field included the whole `data-testid="tracklist-footer-description"`

ie:

> January 27, 2023
> 14 Songs, 57 minutes
> Quality Control Music/Motown Records; ℗ 2023 Quality Control Music, LLC, under exclusive license to UMG Recordings, Inc.

this is the unnecessary part that is also included:
> January 27, 2023
> 14 Songs, 57 minutes

the only part that is needed:
> Quality Control Music/Motown Records; ℗ 2023 Quality Control Music, LLC, under exclusive license to UMG Recordings, Inc.

My temporary solution is to create a "Replace with regular expression" action:
Replace `.* minutes` with `blank` on the `COPYRIGHT` field.

**Comment by MrBukLau** [comment]
When I use the unmodified Apple Music script, I do not get those unnecessary parts. I only get the copyright part. Did you try redownloading the script from this repository and trying it again?

**Comment by randomuser10800** [comment]
https://user-images.githubusercontent.com/108909664/216629767-ce413d38-d607-4f29-b3d7-e66739e8efde.MOV

Please provide a fix.

**Comment by MrBukLau** [comment]
Ok. I see what the problem is. This issue was not showing up for me if I used the macOS version of Mp3tag, but it did show up when I used the Windows version of Mp3tag. I made some changes to the script regarding the copyright field, so all you guys have to do now is download the latest version from this repository. It should work for both operating systems now.
